---
swagger: "2.0"
info:
  x-ibm-name: "openapi"
  title: "openapi"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/openapi"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  oauth-1:
    type: "oauth2"
    description: ""
    flow: "accessCode"
    scopes:
      scope1: ""
    authorizationUrl: "https://api.us-south.apiconnect.appdomain.cloud/chocopon0899gmailcom-dev/sb/oauthprovider/oauth2/authorize"
    tokenUrl: "https://api.us-south.apiconnect.appdomain.cloud/chocopon0899gmailcom-dev/sb/oauthprovider/oauth2/token"
  clientIdHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Id"
security:
- clientIdHeader: []
  oauth-1:
  - "scope1"
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - gatewayscript:
        title: "gatewayscript"
        version: "1.0.0"
        source: "apim.setvariable('message.headers.resource-owner', apim.getvariable('oauth.resource-owner'));"
    - invoke:
        target-url: "https://dataappcloud.mybluemix.net/api/Open/UserInfo"
    catch: []
  phase: "realized"
paths:
  /bodyinformation:
    get:
      responses:
        200:
          description: "200 OK"
    post:
      responses:
        200:
          description: "200 OK"
definitions: {}
tags: []
