version: 2.1

orbs:
  maven: circleci/maven@1.1

jobs:
  deploy:
      machine: 
        image: default
      steps:
          - checkout
          - run: ssh ${USER_NAME}@${HOST_NAME} 'touch circleci.flg'
          - run: pwd

workflows:
  test-depoly:
    jobs:
      - maven/test
      - deploy
