version: 2.1

orbs:
  maven: circleci/maven@1.1

jobs:
  deploy:
      machine: 
        image: default
      steps:
          - run: pwd

workflows:
  test-depoly:
    jobs:
      - maven/test
      - deploy
