version: 2.1

orbs:
  maven: circleci/maven@1.1

jobs:
  deploy:
      machine:
          enabled: true
      steps:
          - attach_workspace:
              at:'.'
          - run: pwd

workflows:
  test-depoly:
    jobs:
      - maven/test
      - deploy
