version: 2.1

jobs:
  test:
      machine: 
        image: default
      steps:
        - checkout
        - run:
            command: mvn clean install
        - persist_to_workspace:
            root: '.'
            paths:
              - target
        - run:
            name: Save test results
            command: |
              mkdir -p ~/test-results/junit/
              find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
            when: always
        - store_test_results:
            path: ~/test-results
        - store_artifacts:
            path: ~/test-results/junit

  deploy:
      machine: 
        image: default
      steps:
        - attach_workspace:
            at: '.'
        - add_ssh_keys:
            fingerprints:
              - '3a:5c:be:07:a4:f0:df:4d:04:11:59:90:53:a4:58:55'
        - run: scp target/DataApp.war ${USER_NAME}@${HOST_NAME}:/home/chocopon1
        - run: ssh -t ${USER_NAME}@${HOST_NAME} 'cp /home/chocopon1/DataApp.war /opt/apache-tomcat/webapps'

workflows:
  test-depoly:
    jobs:
      - test
      - deploy:
            requires:
                - test
            filters:
                branches:
                  only: master
